"""Head types: one agent session (Codex TUI, Claude terminal) the product brings up and stops.

`HeadSpec` is the head, `HeadRun` the running instance, `TaskRef` what it was pointed at (card,
sprint or standing instruction). `command` renders a head's shell command from a registry profile.
`runtime` defines the backend boundary `HeadRuntime` with six verbs (`start`, `deliver`, `observe`,
`request_drain`, `stop`, `attach`) returning typed receipts, plus the per-head `TurnLease`,
activity epoch and admission state; a backend serialises its own verbs, so callers need no lock.
The one backend is `runtime.local_pty_head`. `operations` holds shared refusals, `NudgePointer` and
`post_delivery_run`. What a head is told belongs to `prompt_document`.
"""

from __future__ import annotations

from .command import (
    CLAUDE_EFFORTS,
    CODEX_EFFORTS,
    CODEX_LAUNCH_MODES,
    CODEX_TUI_MODE,
    HEAD_BINDING,
    PROMPT_AFTER_START_ADAPTERS,
    PYTHON_SAFE_PATH_FLAG,
    STANDING_BINDING,
    HeadCommand,
    HeadCommandError,
    render_head_command,
    validate_launch_shape,
    with_pid_heartbeat,
    wrap_role_command,
)
from .operations import (
    HeadNudgeFailed,
    HeadOperationError,
    HeadSpawnAborted,
    HeadSpawnFailed,
    HeadStopFailed,
    NudgePointer,
    post_delivery_run,
)
from .run import (
    EXITED,
    FINISHING,
    LIFECYCLE,
    SPAWNED,
    WORKING,
    HeadRun,
    HeadRunError,
    StopInitiator,
    new_run_id,
)
from .runtime import (
    HEAD_ALIVE,
    HEAD_BUSY,
    HEAD_DRAINING,
    HEAD_GONE,
    HEAD_OK,
    HEAD_UNSUPPORTED,
    OBSERVE_INVENTORY_UNREADABLE,
    OBSERVE_NO_ADDRESS,
    OBSERVE_PANE_ABSENT,
    OBSERVE_PANE_DISCONNECTED,
    OBSERVE_READINESS_UNKNOWN,
    RECEIPT_STATUSES,
    AttachReceipt,
    DeliverReceipt,
    DrainReceipt,
    HeadActivity,
    HeadReceipt,
    HeadRuntime,
    ObserveReceipt,
    StartReceipt,
    StopReceipt,
    TurnLease,
    TurnLeaseError,
)
from .spec import DEFAULT_EFFORT, HeadSpec, HeadSpecError, head_spec, load_head_specs
from .task_ref import (
    TASK_CARD,
    TASK_KINDS,
    TASK_SPRINT,
    TASK_STANDING,
    TaskRef,
    TaskRefError,
)

__all__ = [
    "CLAUDE_EFFORTS",
    "CODEX_EFFORTS",
    "CODEX_LAUNCH_MODES",
    "CODEX_TUI_MODE",
    "DEFAULT_EFFORT",
    "EXITED",
    "FINISHING",
    "HEAD_ALIVE",
    "HEAD_BINDING",
    "HEAD_BUSY",
    "HEAD_DRAINING",
    "HEAD_GONE",
    "HEAD_OK",
    "HEAD_UNSUPPORTED",
    "LIFECYCLE",
    "OBSERVE_INVENTORY_UNREADABLE",
    "OBSERVE_NO_ADDRESS",
    "OBSERVE_PANE_ABSENT",
    "OBSERVE_PANE_DISCONNECTED",
    "OBSERVE_READINESS_UNKNOWN",
    "PROMPT_AFTER_START_ADAPTERS",
    "PYTHON_SAFE_PATH_FLAG",
    "RECEIPT_STATUSES",
    "SPAWNED",
    "STANDING_BINDING",
    "TASK_CARD",
    "TASK_KINDS",
    "TASK_SPRINT",
    "TASK_STANDING",
    "WORKING",
    "AttachReceipt",
    "DeliverReceipt",
    "DrainReceipt",
    "HeadActivity",
    "HeadCommand",
    "HeadCommandError",
    "HeadNudgeFailed",
    "HeadOperationError",
    "HeadReceipt",
    "HeadRun",
    "HeadRunError",
    "HeadRuntime",
    "HeadSpawnAborted",
    "HeadSpawnFailed",
    "HeadSpec",
    "HeadSpecError",
    "HeadStopFailed",
    "NudgePointer",
    "ObserveReceipt",
    "StartReceipt",
    "StopInitiator",
    "StopReceipt",
    "TaskRef",
    "TaskRefError",
    "TurnLease",
    "TurnLeaseError",
    "head_spec",
    "load_head_specs",
    "new_run_id",
    "post_delivery_run",
    "render_head_command",
    "validate_launch_shape",
    "with_pid_heartbeat",
    "wrap_role_command",
]
